# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=10)),
                ('forecast', models.CharField(max_length=100)),
                ('max_temp', models.CharField(max_length=5)),
                ('min_temp', models.CharField(max_length=5)),
                ('average_temp', models.CharField(max_length=5)),
            ],
        ),
    ]
