# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('readyInMinutes', models.IntegerField()),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('forecast', models.CharField(max_length=100)),
                ('max_temp', models.FloatField()),
                ('min_temp', models.FloatField()),
                ('average_temp', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipeWeather',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodAPI.Weather'),
        ),
    ]
