# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodAPI', '0002_auto_20170404_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='average_temp',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='weather',
            name='date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='weather',
            name='max_temp',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='weather',
            name='min_temp',
            field=models.CharField(max_length=5),
        ),
    ]
