# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodAPI', '0003_auto_20170413_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipeWeather',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
