# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodAPI', '0003_auto_20170503_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='vegan',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vegetarian',
            field=models.BooleanField(default=False),
        ),
    ]
