# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodAPI', '0004_auto_20170503_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dairy_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='gluten_free',
            field=models.BooleanField(default=False),
        ),
    ]
